// pages/tool/tool.js
Page({
  data:{
    toolList:[
      {
        imgSrc:"http://8.219.238.51/images/tool1.jpg",
        title:"节拍器"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool2.jpg",
        title:"智能识谱"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool3.jpg",
        title:"节奏训练"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool4.jpg",
        title:"吉他和弦"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool5.png",
        title:"曲谱练习"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool6.jpg",
        title:"在线演奏"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool7.jpg",
        title:"音乐社区"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool8.jpg",
        title:"钢琴调音器"
      },
      {
        imgSrc:"http://8.219.238.51/images/tool9.jpg",
        title:"排练助手"
      }
    ]
  }
})